### ISSUE TITLE
Text Overflow in chat bubble

### ISSUE THREAD

**Issue by newnewb** [z0al/react-chat-stuff#2]
The text is overflowing and not wrapping around in the chat bubble, experiencing the same issue on Chrome & Firefox

![chrome windows 10](https://user-images.githubusercontent.com/19394906/47045204-50c8a000-d1a3-11e8-908c-aef61a961d62.PNG)

![firefox ubuntu 18 04](https://user-images.githubusercontent.com/19394906/47045213-57571780-d1a3-11e8-86b4-a93e87cc69bc.PNG)

Firefox Version 62.0.3 (64-bit)
Chrome Version 69.0.3497.100

**Comment by z0al** [comment]
Oh, thanks for reporting!

This was caused by ebc4dd6 by introducing `white-space: pre` which changes the default behavior of the `<span>`. 

We need to respect new lines using another way then.
